{% set name = "pytorch-ignite" %}
{% set version = "0.4.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorch-ignite-{{ version }}.tar.gz
  sha256: ee31096a58679417097ef7f3f27d88bec40b789ac5e13cd9ed08bc89ca8ce2e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.3,<2

test:
  imports:
    - ignite
    - ignite.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/ignite
  summary: A lightweight library to help with training neural networks in PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
