{% set name = "pytorch-ignite" %}
{% set version = "0.5.2" %}
{% set python_min = python_min|default("3.6") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch_ignite-{{ version }}.tar.gz
  sha256: 63bdbafe3fb76bf243e4c7fa4b71c89a652fece6c4c2f6e3c5b448ac74447d98

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.3

test:
  imports:
    - ignite
    - ignite.base
  commands:
    - pip check
  requires:
    - packaging
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/ignite
  summary: A lightweight library to help with training neural networks in PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
