{% set name = "pytorch-ignite" %}
{% set version = "0.5.1" %}
{% set python_min = python_min|default("3.6") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch-ignite-{{ version }}.tar.gz
  sha256: f41050bb0f85da6a4e5483cbc584ddf300382f537cd2f31cbb05ad62b8a6682e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.3

test:
  imports:
    - ignite
    - ignite.base
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/ignite
  summary: A lightweight library to help with training neural networks in PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
