{% set name = "pytorch-ignite" %}
{% set version = "0.5.5" %}
{% set python_min = python_min|default("3.10") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch_ignite-{{ version }}.tar.gz
  sha256: 2c14de75c939a3cc06d2e7de00b1e0a261917ef9bd874dac2e69d789dfa9cc64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.24.2
  run:
    - python >={{ python_min }}
    - pytorch >=2.2,<3
    - packaging

test:
  imports:
    - ignite
    - ignite.base
  commands:
    - pip check
  requires:
    - packaging
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/ignite
  summary: A lightweight library to help with training neural networks in PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
